steps:
  - label: "update docker image"
    command: "docker pull mockserver/mockserver:grunt"

  - wait

  - label: "build"
    command: "docker run -v $(pwd):/build/mockserver-client-node -w /build/mockserver-client-node -a stdout -a stderr -e BUILDKITE_BRANCH=$BUILDKITE_BRANCH mockserver/mockserver:grunt /build/mockserver-client-node/scripts/buildkite_quick_build.sh"
